// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"time"
)

type User struct {
	ID                   int32
	Email                sql.NullString
	Username             sql.NullString
	Firstname            sql.NullString
	Lastname             sql.NullString
	Password             sql.NullString
	FacebookID           sql.NullString
	ResetPasswordToken   sql.NullString
	ResetPasswordExpires sql.NullString
	IsPremium            bool
	PremiumLevel         int32
	StripeCustomerID     sql.NullString
	IsDeleted            bool
	CreatedAt            time.Time
	UpdatedAt            time.Time
}
