// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"time"
)

type Pet struct {
	ID                 int32
	Name               string
	Dateofbirth        sql.NullTime
	Dateofbirthexact   sql.NullBool
	Imageurl           sql.NullString
	AboutText          sql.NullString
	Species            sql.NullString
	Breed              sql.NullString
	Sex                sql.NullString
	Ispubliclyviewable bool
	Likeshidden        bool
	Skillshidden       bool
	Goalshidden        bool
	Titleshidden       bool
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type User struct {
	ID                   int32
	Email                sql.NullString
	Username             sql.NullString
	Firstname            sql.NullString
	Lastname             sql.NullString
	Password             sql.NullString
	FacebookID           sql.NullString
	ResetPasswordToken   sql.NullString
	ResetPasswordExpires sql.NullString
	IsPremium            bool
	PremiumLevel         int32
	StripeCustomerID     sql.NullString
	IsDeleted            bool
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type Userpet struct {
	Userid           int32
	Petid            int32
	PermissionsLevel int32
	Active           bool
	Hidden           bool
	CreatedAt        time.Time
	UpdatedAt        time.Time
}
