// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: pets.sql

package database

import (
	"context"
	"database/sql"
)

const createPet = `-- name: CreatePet :one
INSERT INTO pet(name, imageUrl, created_at, updated_at)
VALUES (
    $1,
    $2,
    NOW(),
    NOW()
)
RETURNING id, name, dateofbirth, dateofbirthexact, imageurl, about_text, species, breed, sex, ispubliclyviewable, likeshidden, skillshidden, goalshidden, titleshidden, created_at, updated_at
`

type CreatePetParams struct {
	Name     string
	Imageurl sql.NullString
}

func (q *Queries) CreatePet(ctx context.Context, arg CreatePetParams) (Pet, error) {
	row := q.db.QueryRowContext(ctx, createPet, arg.Name, arg.Imageurl)
	var i Pet
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Dateofbirth,
		&i.Dateofbirthexact,
		&i.Imageurl,
		&i.AboutText,
		&i.Species,
		&i.Breed,
		&i.Sex,
		&i.Ispubliclyviewable,
		&i.Likeshidden,
		&i.Skillshidden,
		&i.Goalshidden,
		&i.Titleshidden,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserPet = `-- name: CreateUserPet :one
INSERT INTO UserPets(userId, petId, permissions_level, active, created_at, updated_at)
VALUES (
    $1,
    $2,
    $3,
    $4,
    NOW(),
    NOW()
)
RETURNING userid, petid, permissions_level, active, hidden, created_at, updated_at
`

type CreateUserPetParams struct {
	Userid           int32
	Petid            int32
	PermissionsLevel int32
	Active           bool
}

func (q *Queries) CreateUserPet(ctx context.Context, arg CreateUserPetParams) (Userpet, error) {
	row := q.db.QueryRowContext(ctx, createUserPet,
		arg.Userid,
		arg.Petid,
		arg.PermissionsLevel,
		arg.Active,
	)
	var i Userpet
	err := row.Scan(
		&i.Userid,
		&i.Petid,
		&i.PermissionsLevel,
		&i.Active,
		&i.Hidden,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePets = `-- name: DeletePets :exec
DELETE FROM pet
`

func (q *Queries) DeletePets(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deletePets)
	return err
}

const deleteUserPets = `-- name: DeleteUserPets :exec
DELETE FROM UserPets
`

func (q *Queries) DeleteUserPets(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteUserPets)
	return err
}
