name: ci

on:
  pull_request:
    branches: [main]
    runs-on: ubuntu-latest

env:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: animal_training_journal_test
  POSTGRES_HOST: localhost
  POSTGRES_PORT: 5432

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
        ports:
          - 5432:5432

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.0"

      - name: install goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: Add ${HOME}/go/bin to PATH
        run: echo "${HOME}/go/bin" >> $GITHUB_PATH

      - name: check goose version
        run: goose -version

      - name: run goose migrations
        run: ./scripts/init_test.sh

      - name: Run tests
        run: go test ./... -cover

      - name: install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Run gosec
        run: gosec ./...

  style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.0"

      - name: Check style
        run: test -z $(go fmt ./...)

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: staticcheck ./...
